### ISSUE TITLE
请问文章中一些符号表示什么意思

### ISSUE THREAD

**Issue by shuqincao** [HKUDS/CL4ST#1]
请问大佬，公式（1）和（2）中的h_u^(0)， h_v^(0)，x_u^(0)，x_v^(0), h_u^(1),h_v^(1) 表示什么含义

**Comment by tjb-tech** [comment]
您好，非常感谢关注我们的工作！h_v^(0)， h_u^(0)分别代表v结点和它的邻居u结点，h向量的数字上标代表迭代的层数，x代表初始图特征向量。
